services:
  surecast:
    build: .
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./recordings:/app/recordings
      - ./uploads:/app/uploads
      - ./episodes:/app/episodes
